### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by cpitclaudel** [barghouthi/cav16-aec#2]
Hi,

The website to download the VM seems to be down:

![screenshot from 2016-04-21 10 34 39](https://cloud.githubusercontent.com/assets/8181630/14712824/b5b6cc12-07ac-11e6-8669-ddd95578e0d0.png)

And wget's output:

```
$ wget www.cs.wisc.edu/%7Eaws/cav2016.ova
--2016-04-21 10:33:03--  http://www.cs.wisc.edu/%7Eaws/cav2016.ova
Resolving www.cs.wisc.edu (www.cs.wisc.edu)... 128.105.7.31
Connecting to www.cs.wisc.edu (www.cs.wisc.edu)|128.105.7.31|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

Is there a mirror that I could use?
Thanks!

**Comment by barghouthi** [comment]
Working on it.

**Comment by barghouthi** [comment]
If you need to start now, I recommend installing your Ubuntu VM, as it might take a couple of hours for sysadmin to reply.

**Comment by barghouthi** [comment]
Mirror: https://drive.google.com/file/d/0B16Szzr2Ku7WRWtUUHJXbXQ3OTg/view?usp=sharing

**Comment by cpitclaudel** [comment]
I already have a Vagrant setup :) I just need to install things in the official VM. Downloading from Google, thanks!

**Comment by cpitclaudel** [comment]
This worked great; belated thanks! (Btw, I coudn't find a timeline of the artifact evaluation; is there a timeframe for requests for clarification (in the style of POPL, for example?). And is it known when results will be announced? Thanks!)

**Comment by barghouthi** [comment]
Unfortunately, due to the short timeframe we have before having to inform Springer of accepted papers, and the large number of submissions, there will be no time for formal requests/clarification. Results will be announced May 20.

**Comment by cpitclaudel** [comment]
Great, thanks for the clarification :)
